### ISSUE TITLE
add obfs4 and meek support!

### ISSUE THREAD

**Issue by n8fr8** [JRock007/Tob#1]
Work is being done to get Obfs4 working on iOS and linked into Onion Browser. 

https://github.com/mtigas/iObfs/

I think you should consider adding it in to your promising effort here! The QR code scanning camera feature you have is definitely appreciated.

**Comment by n8fr8** [comment]
More here: https://github.com/OnionBrowser/iOS-OnionBrowser/tree/iobfs

**Comment by JRock007** [comment]
Thanks for your feedback!
I'll definitely look into it, and try to implement it as soon as possible. I may wait a bit to make sure the implementation is stable though.
