### ISSUE TITLE
Wrong IP address after requesting new identity

### ISSUE THREAD

**Issue by JRock007** [JRock007/Tob#13]
The Tor panel doesn't seem to update the user's IP address correctly.
A new request is sent out each time it is opened, but the result seems to be cached somewhere.

The real IP address does change, as visiting a webpage directly in the browser gives the right IP address.

**Comment by AlekseyGerbyn** [comment]
Try to call

[appDelegate.tor disableNetwork];
[appDelegate.tor enableNetwork];

Before calling:

[appDelegate.tor requestNewTorIdentity];

**Comment by decidion** [comment]
@AlekseyGerbyn  у Вас получилось исправить ошибку с крешами в:
[_HTTPStream close]; 
при переходах назад/вперед в браузере?
