### ISSUE TITLE
licensing problems

### ISSUE THREAD

**Issue by jcs** [JRock007/Tob#3]
It has been brought to my attention that a lot of the code for this project is based off of my [endless](https://github.com/jcs/endless) browser, which has a [restrictive license](https://github.com/jcs/endless/blob/master/LICENSE) forbidding binary distribution.  I explicitly mention in my [LICENSE](https://github.com/jcs/endless/blob/master/LICENSE) file that you cannot redistribute my code in an app on the App Store, which you are doing with your [The Onion Browser](https://itunes.apple.com/us/app/the-onion-browser/id1063151782?mt=8) app.  (As an aside, I think it's pretty rude to undercut Mike Tigas' [Onion Browser](https://itunes.apple.com/us/app/onion-browser/id519296448?mt=8) that he charges a dollar for by just taking all of his open source code and putting it in your free app.)

You removed my LICENSE file and added [your own](https://github.com/JRock007/The-Onion-Browser/blob/master/LICENSE) despite there being huge parts of your code still based on my unmodified work, in addition to removing my copyright declaration and adding permissive terms that my original license does not permit.  That is not legal, and is also confusing since [files](https://github.com/JRock007/The-Onion-Browser/blob/master/OnionBrowser/OnionBrowser/HTTPSEverywhere.m) [of](https://github.com/JRock007/The-Onion-Browser/blob/master/OnionBrowser/OnionBrowser/HostSettings.m) [mine](https://github.com/JRock007/The-Onion-Browser/blob/master/OnionBrowser/OnionBrowser/SSLCertificate.m) in your project still point to a LICENSE file for distribution terms, which you have completely changed.

**Comment by yegortimoshenko** [comment]
You can enforce your license by [sending a takedown notice to GitHub](https://help.github.com/articles/dmca-takedown-policy/) and [starting an App Store content dispute](http://www.apple.com/legal/internet-services/itunes/appstorenotices/#?lang=en).
