### ISSUE TITLE
Tor stuck on "Connecting to directory server" using IPv6

### ISSUE THREAD

**Issue by dolar2006** [JRock007/Tob#5]
Hi,
Tor doesn't connect at all when using IPv6 network. It's stuck on Connecting to directory server.

This was the console log, 
BOOTSTRAP PROGRESS=5 TAG=conn_dir SUMMARY="Connecting to directory server" WARNING="Network is unreachable" REASON=NOROUTE

**Comment by JRock007** [comment]
This should have been fixed by a8cc7ba
