### ISSUE TITLE
Lexical or Preprocessor Issue Group

### ISSUE THREAD

**Issue by Taherismail17** [JRock007/Tob#7]
There is an issue when building: #include "or/or.h" has the error /Users/(MyName)/Downloads/Tob-master/Tob/ThirdParty/Tor/TorWrapper.h:10:10: 'or/or.h' file not found

**Comment by JRock007** [comment]
This happens because Xcode can't find the dependencies required by this project.
Did you run the build.sh script?

**Comment by Taherismail17** [comment]
I'm not sure, I'm fairly new to Xcode (only 14😂). Will try running that. Is that in Xcode scheme?

**Comment by JRock007** [comment]
No, it's a file you have to run manually from Terminal.
It is located in Tob-master/Tob. To run it, just type in Terminal:
cd PATH_TO_THE_FOLDER/Tob-master/Tob
./build.sh

It will most likely fail with "COULD NOT VERIFY PACKAGE SIGNATURE...". You can either download the signatures from libssl, libevent and Tor or change VERIFYGPG to false in build-tor.sh, build-libssl.sh and build-libevent.sh.

**Comment by JRock007** [comment]
I updated the build script and added a build section in the readme to make it clearer how to build the dependencies.
