### ISSUE TITLE
Bookmar deletion on pressing "Cancel" button

### ISSUE THREAD

**Issue by Drag11** [JRock007/Tob#8]
Is this a feature or a bug?
Seems like a bug, since we delete the bookmark page if a user click "Cancel" while editing the bookmark

```
- (void)goBack {
    AppDelegate *appDelegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    NSError *error = nil;

    [appDelegate.managedObjectContext deleteObject:bookmark];
    
    error = nil;
    if (![appDelegate.managedObjectContext save:&error]) {
        // Handle the error.
    }
    
    [self dismissViewControllerAnimated:YES completion:nil];
}

**Comment by JRock007** [comment]
You are right, this is a bug. The bookmark should only be removed if the user was creating it, not during edition. I added a flag to differentiate the cases.
Thanks for reporting that !
